import path from 'path';
import { fileURLToPath } from 'url';

import { defineConfig } from 'vitest/config';

const root = path.dirname(fileURLToPath(import.meta.url));
const pkg = (...parts: string[]) => path.resolve(root, 'packages', ...parts);

export default defineConfig({
  // Workspace packages resolve straight to their TypeScript sources so tests
  // never depend on a prior `npm run build:packages` (dist may be stale/absent
  // in test runs). Longest keys first — subpath aliases must win over the
  // package root.
  resolve: {
    alias: {
      '@skoobi/shared/logger': pkg('shared', 'src', 'logger.ts'),
      '@skoobi/shared/env': pkg('shared', 'src', 'env.ts'),
      '@skoobi/shared/log-sanitize': pkg('shared', 'src', 'log-sanitize.ts'),
      '@skoobi/shared/media-manifest': pkg('shared', 'src', 'media-manifest.ts'),
      '@skoobi/shared/telegram-jid': pkg('shared', 'src', 'telegram-jid.ts'),
      '@skoobi/shared/telegram-identity': pkg('shared', 'src', 'telegram-identity.ts'),
      '@skoobi/shared/channel-types': pkg('shared', 'src', 'channel-types.ts'),
      '@skoobi/shared/group-folder': pkg('shared', 'src', 'group-folder.ts'),
      '@skoobi/shared/private-admin': pkg('shared', 'src', 'private-admin.ts'),
      '@skoobi/shared/safe-child-write': pkg(
        'shared',
        'src',
        'safe-child-write.ts',
      ),
      '@skoobi/shared/binary-paths': pkg(
        'shared',
        'src',
        'binary-paths.ts',
      ),
      '@skoobi/shared/assistant-name': pkg(
        'shared',
        'src',
        'assistant-name.ts',
      ),
      '@skoobi/shared': pkg('shared', 'src', 'index.ts'),
      '@skoobi/billing/quota': pkg('billing', 'src', 'quota.ts'),
      '@skoobi/billing': pkg('billing', 'src', 'index.ts'),
      '@skoobi/core/types': pkg('core', 'src', 'orchestrator', 'types.ts'),
      '@skoobi/core/config': pkg('core', 'src', 'orchestrator', 'config.ts'),
      '@skoobi/core/timezone': pkg('core', 'src', 'orchestrator', 'timezone.ts'),
      '@skoobi/core/router': pkg('core', 'src', 'orchestrator', 'router.ts'),
      '@skoobi/core/channel-registry': pkg('core', 'src', 'orchestrator', 'channel-registry.ts'),
      '@skoobi/core/tenant-registry': pkg('core', 'src', 'orchestrator', 'tenant-registry.ts'),
      '@skoobi/core/event-store': pkg('core', 'src', 'orchestrator', 'event-store.ts'),
      '@skoobi/core/db': pkg('core', 'src', 'orchestrator', 'db.ts'),
      '@skoobi/core/whatsapp-observer': pkg('core', 'src', 'orchestrator', 'whatsapp-observer.ts'),
      '@skoobi/core/ingestion': pkg('core', 'src', 'orchestrator', 'ingestion.ts'),
      '@skoobi/core/calendar-adapter': pkg('core', 'src', 'orchestrator', 'calendar-adapter.ts'),
      '@skoobi/core/group-queue': pkg('core', 'src', 'orchestrator', 'group-queue.ts'),
      '@skoobi/core/process-tree': pkg('core', 'src', 'orchestrator', 'process-tree.ts'),
      '@skoobi/core/skill-registry': pkg('core', 'src', 'orchestrator', 'skill-registry.ts'),
      '@skoobi/core/run-activity': pkg('core', 'src', 'orchestrator', 'run-activity.ts'),
      '@skoobi/core/instructions': pkg('core', 'src', 'orchestrator', 'instructions.ts'),
      '@skoobi/core/persona-registry': pkg('core', 'src', 'orchestrator', 'persona-registry.ts'),
      '@skoobi/core/mount-security': pkg('core', 'src', 'orchestrator', 'mount-security.ts'),
      '@skoobi/core/credential-proxy': pkg('core', 'src', 'orchestrator', 'credential-proxy.ts'),
      '@skoobi/core/extensions': pkg('core', 'src', 'orchestrator', 'extensions.ts'),
      '@skoobi/core/extension-manifest': pkg('core', 'src', 'orchestrator', 'extension-manifest.ts'),
      '@skoobi/core/extension-loader': pkg('core', 'src', 'orchestrator', 'extension-loader.ts'),
      '@skoobi/core/sender-allowlist': pkg('core', 'src', 'orchestrator', 'sender-allowlist.ts'),
      '@skoobi/core/remote-control': pkg('core', 'src', 'orchestrator', 'remote-control.ts'),
      '@skoobi/core/transcript-sweep': pkg('core', 'src', 'orchestrator', 'transcript-sweep.ts'),
      '@skoobi/core/transcript-rotation': pkg('core', 'src', 'orchestrator', 'transcript-rotation.ts'),
      '@skoobi/core/outbound-router': pkg('core', 'src', 'orchestrator', 'outbound-router.ts'),
      '@skoobi/core/ipc': pkg('core', 'src', 'orchestrator', 'ipc.ts'),
      '@skoobi/core/task-scheduler': pkg('core', 'src', 'orchestrator', 'task-scheduler.ts'),
      '@skoobi/core/live-mode': pkg('core', 'src', 'orchestrator', 'live-mode.ts'),
      '@skoobi/core/shadow-mode': pkg('core', 'src', 'orchestrator', 'shadow-mode.ts'),
      '@skoobi/core/tool-registry': pkg('core', 'src', 'orchestrator', 'tool-registry.ts'),
      '@skoobi/core/runtimes/sandbox-runner': pkg('core', 'src', 'runtimes', 'sandbox-runner.ts'),
      '@skoobi/core/runtimes/container-runner': pkg('core', 'src', 'runtimes', 'container-runner.ts'),
      '@skoobi/core/runtimes/container-runtime': pkg('core', 'src', 'runtimes', 'container-runtime.ts'),
      '@skoobi/core/message-loop': pkg('core', 'src', 'orchestrator', 'message-loop.ts'),
      '@skoobi/core/cost-tracking': pkg('core', 'src', 'cost-tracking', 'index.ts'),
      '@skoobi/core/webhook/server': pkg('core', 'src', 'webhook', 'server.ts'),
      '@skoobi/core/webhook': pkg('core', 'src', 'webhook', 'index.ts'),
      '@skoobi/core': pkg('core', 'src', 'orchestrator', 'index.ts'),
      '@skoobi/dashboard/server': pkg('dashboard', 'src', 'server.ts'),
      '@skoobi/dashboard': pkg('dashboard', 'src', 'index.ts'),
      '@skoobi/providers/model-gateway': pkg('providers', 'src', 'model-gateway.ts'),
      '@skoobi/providers/codex-subscription-gateway': pkg('providers', 'src', 'codex-subscription-gateway.ts'),
      '@skoobi/providers/search-gateway': pkg('providers', 'src', 'search-gateway.ts'),
      '@skoobi/providers/image-gateway': pkg('providers', 'src', 'image-gateway.ts'),
      '@skoobi/providers/provider-circuit-breaker': pkg('providers', 'src', 'provider-circuit-breaker.ts'),
      '@skoobi/providers/provider-failover': pkg('providers', 'src', 'provider-failover.ts'),
      '@skoobi/providers/truthfulness': pkg('providers', 'src', 'truthfulness.ts'),
      '@skoobi/providers': pkg('providers', 'src', 'index.ts'),
      '@skoobi/payments/payment-gateway': pkg('payments', 'src', 'payment-gateway.ts'),
      '@skoobi/payments/payment-service': pkg('payments', 'src', 'payment-service.ts'),
      '@skoobi/payments/payment-plans': pkg('payments', 'src', 'payment-plans.ts'),
      '@skoobi/payments/payment-activation': pkg('payments', 'src', 'payment-activation.ts'),
      '@skoobi/payments': pkg('payments', 'src', 'index.ts'),
      '@skoobi/channel-telegram/photo-telegram': pkg('channel-telegram', 'src', 'photo-telegram.ts'),
      '@skoobi/channel-telegram/audio-telegram': pkg('channel-telegram', 'src', 'audio-telegram.ts'),
      '@skoobi/channel-telegram/video-telegram': pkg('channel-telegram', 'src', 'video-telegram.ts'),
      '@skoobi/channel-telegram/document-telegram': pkg('channel-telegram', 'src', 'document-telegram.ts'),
      '@skoobi/channel-telegram/admin-storage': pkg('channel-telegram', 'src', 'admin-storage.ts'),
      '@skoobi/channel-telegram/telegram-bot-config': pkg('channel-telegram', 'src', 'telegram-bot-config.ts'),
      '@skoobi/channel-telegram/telegram': pkg('channel-telegram', 'src', 'telegram.ts'),
      '@skoobi/channel-telegram/wiring': pkg('channel-telegram', 'src', 'wiring.ts'),
      '@skoobi/channel-telegram/photo-caption': pkg('channel-telegram', 'src', 'photo-caption.ts'),
      '@skoobi/channel-telegram': pkg('channel-telegram', 'src', 'index.ts'),
      '@skoobi/channel-whatsapp/whatsapp': pkg('channel-whatsapp', 'src', 'whatsapp.ts'),
      '@skoobi/channel-whatsapp/whatsapp-media': pkg('channel-whatsapp', 'src', 'whatsapp-media.ts'),
      '@skoobi/channel-whatsapp/wiring': pkg('channel-whatsapp', 'src', 'wiring.ts'),
      '@skoobi/channel-whatsapp': pkg('channel-whatsapp', 'src', 'index.ts'),
      '@skoobi/memory/memory-context': pkg('memory', 'src', 'memory-context.ts'),
      '@skoobi/memory/memory-curator': pkg('memory', 'src', 'memory-curator.ts'),
      '@skoobi/memory/user-memory-migration': pkg('memory', 'src', 'user-memory-migration.ts'),
      '@skoobi/memory': pkg('memory', 'src', 'index.ts'),
      '@skoobi/voice-stt': pkg('voice-stt', 'src', 'index.ts'),
      '@skoobi/voice-tts': pkg('voice-tts', 'src', 'index.ts'),
    },
  },
  test: {
    include: [
      'src/**/*.test.ts',
      'packages/**/src/**/*.test.ts',
      'agent/runner/src/**/*.test.ts',
      'setup/**/*.test.ts',
      'scripts/**/*.test.mjs',
    ],
    setupFiles: ['setup/vitest-env.ts'],
  },
});
